# Generated by Django 6.0 on 2025-12-14 05:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("floor", models.IntegerField()),
                ("section", models.CharField(max_length=1)),
                ("slot_number", models.CharField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("BIKE", "2 Wheeler"),
                            ("CAR", "4 Wheeler"),
                            ("TRUCK", "Heavy Vehicle"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=12, unique=True)),
                ("vehicle_number", models.CharField(max_length=20)),
                ("vehicle_type", models.CharField(max_length=10)),
                (
                    "check_in_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                ("paid_amount", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parking.slot",
                    ),
                ),
            ],
        ),
    ]
