# Generated by Django 6.0 on 2026-01-05 12:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                (
                    "price_increment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        max_length=1,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]$", "Section must be a single uppercase letter."
                            )
                        ],
                    ),
                ),
                ("slot_number", models.IntegerField()),
                ("is_available", models.BooleanField(db_index=True, default=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="parking.floor"
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parking.vehicletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                ("vehicle_number", models.CharField(db_index=True, max_length=20)),
                ("phone", models.CharField(db_index=True, max_length=15)),
                ("check_in", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "check_out",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "initial_payment",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, db_index=True, max_length=254, null=True
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parking.slot",
                    ),
                ),
                (
                    "vehicle_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="parking.vehicletype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=8),
                ),
                ("base_hours", models.IntegerField(default=5)),
                (
                    "extra_per_hour",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=8),
                ),
                (
                    "vehicle_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="parking.vehicletype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(
                fields=["floor", "vehicle_type", "is_available"],
                name="parking_slo_floor_i_5e4b20_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together={("floor", "section", "slot_number")},
        ),
    ]
