# Generated by Django 6.0 on 2025-12-14 05:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("price_increment", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ParkingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("BIKE", "2 Wheeler"), ("CAR", "4 Wheeler")],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("base_price", models.IntegerField()),
                ("base_hours", models.IntegerField(default=5)),
                ("extra_per_hour", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="slot",
            name="section",
            field=models.CharField(
                choices=[
                    ("A", "A"),
                    ("B", "B"),
                    ("C", "C"),
                    ("D", "D"),
                    ("E", "E"),
                    ("F", "F"),
                    ("G", "G"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="slot",
            name="slot_number",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="slot",
            name="vehicle_type",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="slot",
            name="floor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="parking.floor"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="slot",
            unique_together={("floor", "section", "slot_number")},
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=20)),
                ("phone", models.CharField(max_length=15)),
                ("vehicle_type", models.CharField(max_length=10)),
                ("check_in", models.DateTimeField(default=django.utils.timezone.now)),
                ("check_out", models.DateTimeField(blank=True, null=True)),
                ("initial_payment", models.IntegerField(default=0)),
                ("final_amount", models.IntegerField(blank=True, null=True)),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="parking.slot",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ParkingTicket",
        ),
    ]
