# Generated by Django 6.0 on 2025-12-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0002_floor_parkingconfig_alter_slot_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parkingconfig",
            name="base_price",
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="parkingconfig",
            name="extra_per_hour",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="slot",
            name="section",
            field=models.CharField(max_length=1),
        ),
    ]
