# Generated by Django 6.0 on 2025-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0003_alter_parkingconfig_base_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
        ),
    ]
