# Generated by Django 6.0 on 2025-12-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0004_ticket_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
