# Generated by Django 6.0 on 2025-12-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0005_ticket_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slot",
            name="is_available",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="check_out",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="email",
            field=models.EmailField(
                blank=True, db_index=True, max_length=254, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="phone",
            field=models.CharField(db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="vehicle_number",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name="slot",
            index=models.Index(
                fields=["floor", "vehicle_type", "is_available"],
                name="parking_slo_floor_i_dc3098_idx",
            ),
        ),
    ]
